server:
  port : 9090
  stored:
    file:
      path : D:\\project_web\\gallery\\files\\

spring:
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ybh4953@gmail.com
    password: smtclknpfjntqevx
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  messages:
    basename: messages/error
    encoding: UTF-8
    use-code-as-default-message: true


  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:13306/springDB
    username: root
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  thymeleaf:
    cache: false
    check-template-location: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
    restart:
      enabled: true

#mybatis 설정
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

#불필요 로그 끈다
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: OFF
      thymeleaf: OFF
